name: Hello  Universe
on:
  push:
    branches:
      - main
  workflow_dispach:
jobs:
  build_and_test:
    runs-on: ubuntu-20.04
    steps:
      - name: Clone Code
        uses: actions/checkout@v2
      - name : Compile Java File
        shell: bash
        run: javac Main.java
      - name: Run Java File
        shell: bash
        run: java Main

   